---
output: 
  word_document:
    reference_docx: CASTemplate2.docx
---

It’s ridiculous to think that anyone can learn R in a day. What we hope to accomplish is to learn what R is and why actuaries should think about adding it to their toolkit. To do this, we’ll walk through some basic practical exercises and emphasize the power and flexibility of R.

#### AM Session

Grab a muffin and some coffee and get ready to learn!

* A brief history of R
* "It's not working!" Making sure that R is installed and functioning
* "This doesn't look like a spreadsheet." Loading and saving data
* Linear models
* Introduction to data visualization 

#### PM Session

Still with us? The afternoon will focus on problems that are specific to actuaries. In addition, we’ll touch on some of the advanced tools that aren’t available in a typical spreadsheet program.

* Loss reserving in R
* Fitting size of loss distributions
* Simulation
* Intermediate data visualization
* Basic machine learning

If participants want to get anything out of the workshop, they should bring their own laptop, with R and RStudio already installed. Installation instructions will be sent via e-mail and available on the internet prior to the workshop.

Not required, but strongly recommended is patience, enthusiasm and a sense of humor. R is difficult, but will give back everything you put into it.